syntax = "proto3";

package az.fitnest.storage;

option java_multiple_files = true;
option java_package = "az.fitnest.storage.grpc";
option java_outer_classname = "StorageProto";

service StorageService {
  rpc UploadFile(stream UploadFileRequest) returns (UploadFileResponse);
  rpc GetDownloadUrl(GetDownloadUrlRequest) returns (GetDownloadUrlResponse);
  rpc DownloadFile(DownloadFileRequest) returns (stream DownloadFileResponse);
  rpc DeleteFiles(DeleteFilesRequest) returns (DeleteFilesResponse);
}

message UploadFileRequest {
  oneof request {
    FileMetadata metadata = 1;
    bytes chunk_data = 2;
  }
}

message FileMetadata {
  string filename = 1;
  string directory = 2;
  string content_type = 3;
  string old_path = 4;
}

message UploadFileResponse {
  bool success = 1;
  string message = 2;
  StorageFileData data = 3;
}

message StorageFileData {
  string path = 1;
  int64 size = 2;
  string md5 = 3;
  int64 fs_id = 4;
}

message GetDownloadUrlRequest {
  string file_id = 1;
}

message GetDownloadUrlResponse {
  bool success = 1;
  string message = 2;
  string download_url = 3;
}

message DownloadFileRequest {
  string file_id = 1;
}

message DownloadFileResponse {
  oneof response {
    FileMetadata metadata = 1;
    bytes file_data = 2;
  }
}

message DeleteFilesRequest {
  repeated string paths = 1;
}

message DeleteFilesResponse {
  bool success = 1;
  string message = 2;
}
