/*
 * Decompiled with CFR 0.152.
 */
package az.fitnest.catalog.service;

import az.fitnest.catalog.dto.DurationOptionDto;
import az.fitnest.catalog.dto.MembershipPresetDto;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

public class MembershipPresetsProvider {
    public static List<MembershipPresetDto> getPresets() {
        ArrayList<MembershipPresetDto> list = new ArrayList<MembershipPresetDto>();
        list.add(MembershipPresetDto.builder().name("Bronze").options(Arrays.asList(DurationOptionDto.builder().durationMonths(1).priceStandard(new BigDecimal("50")).priceDiscounted(new BigDecimal("40")).entryLimit(12).freezeDays(null).services(Arrays.asList("Gym access only", "Free workout program")).build(), DurationOptionDto.builder().durationMonths(3).priceStandard(new BigDecimal("150")).priceDiscounted(new BigDecimal("120")).entryLimit(12).freezeDays(null).services(Arrays.asList("Gym access only", "Free workout program")).build(), DurationOptionDto.builder().durationMonths(6).priceStandard(new BigDecimal("330")).priceDiscounted(new BigDecimal("300")).entryLimit(13).freezeDays(null).services(Arrays.asList("Gym access only", "Free workout program")).build(), DurationOptionDto.builder().durationMonths(12).priceStandard(new BigDecimal("660")).priceDiscounted(new BigDecimal("600")).entryLimit(15).freezeDays(null).services(Arrays.asList("Gym access only", "Free workout program")).build())).build());
        list.add(MembershipPresetDto.builder().name("Silver").options(Arrays.asList(DurationOptionDto.builder().durationMonths(1).priceStandard(new BigDecimal("75")).priceDiscounted(new BigDecimal("65")).entryLimit(12).freezeDays(null).services(Arrays.asList("Personal accident insurance", "Sportswear store \u2013 5% discount", "Sports nutrition \u2013 5% discount", "Cosmetology \u2013 5% discount", "Free workout program")).build(), DurationOptionDto.builder().durationMonths(3).priceStandard(new BigDecimal("225")).priceDiscounted(new BigDecimal("189")).entryLimit(13).freezeDays(null).services(Arrays.asList("Personal accident insurance", "Sportswear store \u2013 5% discount", "Sports nutrition \u2013 5% discount", "Cosmetology \u2013 5% discount", "Free workout program")).build(), DurationOptionDto.builder().durationMonths(6).priceStandard(new BigDecimal("450")).priceDiscounted(new BigDecimal("366")).entryLimit(14).freezeDays(null).services(Arrays.asList("Personal accident insurance", "Sportswear store \u2013 5% discount", "Sports nutrition \u2013 5% discount", "Cosmetology \u2013 5% discount", "Free workout program")).build(), DurationOptionDto.builder().durationMonths(12).priceStandard(new BigDecimal("900")).priceDiscounted(new BigDecimal("708")).entryLimit(15).freezeDays(null).services(Arrays.asList("Personal accident insurance", "Sportswear store \u2013 5% discount", "Sports nutrition \u2013 5% discount", "Cosmetology \u2013 5% discount", "Free workout program")).build())).build());
        list.add(MembershipPresetDto.builder().name("Gold").options(Arrays.asList(DurationOptionDto.builder().durationMonths(1).priceStandard(new BigDecimal("135")).priceDiscounted(new BigDecimal("115")).entryLimit(16).freezeDays(null).services(Arrays.asList("Personal accident insurance", "Sportswear store \u2013 10% discount", "Sports nutrition \u2013 10% discount", "Cosmetology \u2013 10% discount", "Discount on total bill (SPA and pool excluded)", "Free workout program", "Diet program", "Free nutritionist consultation once per month")).build(), DurationOptionDto.builder().durationMonths(3).priceStandard(new BigDecimal("405")).priceDiscounted(new BigDecimal("335")).entryLimit(17).freezeDays(null).services(Arrays.asList("Personal accident insurance", "Sportswear store \u2013 10% discount", "Sports nutrition \u2013 10% discount", "Cosmetology \u2013 10% discount", "Discount on total bill (SPA and pool excluded)", "Free workout program", "Diet program", "Free nutritionist consultation once per month")).build(), DurationOptionDto.builder().durationMonths(6).priceStandard(new BigDecimal("810")).priceDiscounted(new BigDecimal("649")).entryLimit(18).freezeDays(3).services(Arrays.asList("Personal accident insurance", "Sportswear store \u2013 10% discount", "Sports nutrition \u2013 10% discount", "Cosmetology \u2013 10% discount", "Discount on total bill (SPA and pool excluded)", "Free workout program", "Diet program", "Free nutritionist consultation once per month")).build(), DurationOptionDto.builder().durationMonths(12).priceStandard(new BigDecimal("1620")).priceDiscounted(new BigDecimal("1256")).entryLimit(20).freezeDays(4).services(Arrays.asList("Personal accident insurance", "Sportswear store \u2013 10% discount", "Sports nutrition \u2013 10% discount", "Cosmetology \u2013 10% discount", "Discount on total bill (SPA and pool excluded)", "Free workout program", "Diet program", "Free nutritionist consultation once per month")).build())).build());
        list.add(MembershipPresetDto.builder().name("Platinum").options(Arrays.asList(DurationOptionDto.builder().durationMonths(1).priceStandard(new BigDecimal("190")).priceDiscounted(new BigDecimal("165")).entryLimit(20).freezeDays(null).services(Arrays.asList("Personal accident insurance", "Sportswear store \u2013 15% discount", "Sports nutrition \u2013 15% discount", "Cosmetology \u2013 15% discount", "Discount on total bill (SPA and pool excluded)", "Free workout program", "Tour package discount", "Diet program", "Free nutritionist consultation once per month", "Trainer consultation \u2013 3 times per month")).build(), DurationOptionDto.builder().durationMonths(3).priceStandard(new BigDecimal("570")).priceDiscounted(new BigDecimal("480")).entryLimit(21).freezeDays(2).services(Arrays.asList("Personal accident insurance", "Sportswear store \u2013 15% discount", "Sports nutrition \u2013 15% discount", "Cosmetology \u2013 15% discount", "Discount on total bill (SPA and pool excluded)", "Free workout program", "Tour package discount", "Diet program", "Free nutritionist consultation once per month", "Trainer consultation \u2013 3 times per month")).build(), DurationOptionDto.builder().durationMonths(6).priceStandard(new BigDecimal("1140")).priceDiscounted(new BigDecimal("931")).entryLimit(23).freezeDays(3).services(Arrays.asList("Personal accident insurance", "Sportswear store \u2013 15% discount", "Sports nutrition \u2013 15% discount", "Cosmetology \u2013 15% discount", "Discount on total bill (SPA and pool excluded)", "Free workout program", "Tour package discount", "Diet program", "Free nutritionist consultation once per month", "Trainer consultation \u2013 3 times per month")).build(), DurationOptionDto.builder().durationMonths(12).priceStandard(new BigDecimal("2280")).priceDiscounted(new BigDecimal("1802")).entryLimit(25).freezeDays(4).services(Arrays.asList("Personal accident insurance", "Sportswear store \u2013 15% discount", "Sports nutrition \u2013 15% discount", "Cosmetology \u2013 15% discount", "Discount on total bill (SPA and pool excluded)", "Free workout program", "Tour package discount", "Diet program", "Free nutritionist consultation once per month", "Trainer consultation \u2013 3 times per month")).build())).build());
        return list;
    }
}

